version: "2.1"
services:
      mysql:
        image: mysql:5.6.41
        ports:
          - 3306:3306
        container_name: mysql
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: springbootdb
          MYSQL_PASSWORD: root
          MYSQL_USER: root
        network_mode: "host"
        hostname: localhost
        restart: always
        volumes:
          - /DB/mysql:/var/lib/mysql
        healthcheck:
          test: "exit 0"